### ISSUE TITLE
duplicate node in match?

### ISSUE THREAD

**Issue by hstern2** [yorkyer/edmonds-blossom#2]
from max_matching import Match
unique_edges = [(0, 1), (0, 14), (1, 2), (2, 15), (2, 3), (3, 4), (4, 27), (5, 6), (5, 26), (6, 7), (7, 25), (7, 8), (8, 9), (9, 24), (9, 10), (10, 11), (12, 13), (12, 16), (13, 14), (14, 15), (16, 17), (18, 19), (18, 21), (19, 20), (21, 22), (22, 23), (24, 25), (26, 27)]
edges = unique_edges + [(j,i) for i,j in unique_edges]
match = Match.from_edges(28, edges)
match.maximum_matching()
for n in match.nodes:
    if n.mate is not None:
        i = n.index
        j = n.mate.index
        if i < j:
            print(i,j)

### 9 is duplicated
#0 14
#2 3
#4 27
#5 26
#6 7
#8 9
#9 24
#10 11
#12 13
#16 17
#18 21
#19 20
#22 23

**Comment by yorkyer** [comment]
Hi, the bug is fixed. Thank you for reporting this.

Outcome:
```txt
0 1
2 3
4 27
5 26
6 7
8 9
10 11
12 13
14 15
16 17
18 21
19 20
22 23
24 25
```
